# Karma2 公开仓同步通知（自动生成 — 勿手改 vendor）

| 项 | 值 |
|----|-----|
| 公开仓库 | {{CORE_REPO}} |
| 锁定 commit | `{{CORE_COMMIT}}` |
| 生成时间 (UTC) | {{GENERATED_AT_UTC}} |
| 建议 tag 备注 | {{CORE_TAG}} |
| Alembic（公开 API） | `0020` → `0025`（`0025_trade_pipeline_security`） |

## 导入 Karma2（本包 → ops/release-sync/）

1. 将本目录 **整包合并** 进 Karma2 `ops/release-sync/`（或贵司约定路径）。
2. **`vendor/karma-public-sync/` 必须从本包复制，禁止在私仓手改 vendor 文件。**
3. 更新 `ops/release/CORE_VERSION.lock` → `CORE_COMMIT={{CORE_COMMIT}}`。
4. 按链上部署更新 `deployment-manifest.json`。
5. 合并 `schemas_public/` → Karma2 对应目录（若 OpenAPI/JSON 有 fork，按 `SYNC_PUBLIC_REPO.md` **按需合并**，勿整文件盲替）。
6. 私有仓执行：`./verify-manifest.sh`（或等价 CI）。

## 合并 vendor 后建议（Karma2）

```bash
make -C private-risk-engine contract-sync alignment-guard acceptance
```

## 本基线公开能力摘要

- 阶段一：`/v1/payment-codes`、`/v1/trade/orders/*`、Console trade、预授权/全自动流水线
- OpenClaw：automation-policy、readiness、handoff-confirm、webhook 事件
- 流水线 v2：launch 幂等、`chain_anchor_hash`（testnet/hybrid）、结算 transition 审计
- SDK（#80+）：`karma-openclaw` phase1 MCP、`karma-openmanus` `KarmaRuntimeClient`

## 公开文档

- `docs/PRIVATE_REPO_EXECUTION_CHECKLIST-zh.md`
- `docs/PRIVATE_REPO_PHASE1_CHECKLIST-zh.md`
- `docs/PHASE1_CLAW_MANUS_LIVE_ACCEPTANCE-zh.md`
- `docs/TESTNET_PHASE1_TRADE_ACCEPTANCE-zh.md`

## 重新生成本包（仅公开仓）

```bash
./split-release/prepare-karma2-sync-package.sh \
  --out-dir results/karma2-sync-package \
  --core-commit {{CORE_COMMIT}}
```

---
*Generated by `prepare-karma2-sync-package.sh` — source of truth is public Karma `main`, not this copy.*
