[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
karma_anchor = "2nMJG572zrnQiRpBQf3N7DBEX6Ufiwz4NikxVTcgDMka"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
