"""Build OpenClaw handoff v1 draft from on-chain/off-chain Karma state (read-only helper)."""

from __future__ import annotations

from typing import Any

from sqlalchemy.ext.asyncio import AsyncSession

from core.schemas import TaskStatus, VoucherStatus
from db.models.orm import CapacityModel, TaskContractModel, VoucherModel
from db.stores.settlement_store import PostgresSettlementStore
from karma_openclaw.handoff import HANDOFF_VERSION, validate_handoff_v1


async def build_handoff_draft(
    db: AsyncSession,
    *,
    task_id: str,
    trace_id: str = "",
) -> dict[str, Any]:
    """
    Suggest handoff JSON for operators exporting to OpenClaw.

    ``manual_console_steps_completed`` lists steps inferred from ledger state — the operator
    must confirm each step was done in Console before automation.
    """
    store = PostgresSettlementStore(db)
    settlement = await store.get(task_id)
    contract_row = await db.get(TaskContractModel, task_id)
    warnings: list[str] = []
    inferred: list[str] = []

    voucher_row = None
    if settlement and settlement.voucher_id:
        voucher_row = await db.get(VoucherModel, settlement.voucher_id)

    buyer_id = ""
    seller_id = ""
    bill_credit = None
    if contract_row:
        buyer_id = contract_row.client_agent_id
        seller_id = getattr(contract_row, "worker_agent_id", "") or ""
    if settlement:
        buyer_id = buyer_id or settlement.client_agent_id
        seller_id = seller_id or (settlement.worker_agent_id or "")
        bill_credit = float(settlement.escrow_amount)

    if voucher_row:
        inferred.append("buyer_create_voucher")
        buyer_id = buyer_id or voucher_row.buyer_identity_id
        seller_id = seller_id or voucher_row.seller_identity_id
        bill_credit = bill_credit if bill_credit is not None else float(voucher_row.bill_credit_amount)
        vstat = VoucherStatus(voucher_row.status)
        if vstat == VoucherStatus.ACCEPTED:
            inferred.append("seller_accept_voucher")
        elif vstat == VoucherStatus.CREATED:
            warnings.append("Voucher exists but is not accepted — complete seller accept in Console.")

    if settlement:
        inferred.append("settlement_created")
        st = settlement.status
        if settlement.worker_agent_id and st not in (
            TaskStatus.DRAFT,
            TaskStatus.PENDING,
            TaskStatus.CREATED,
        ):
            inferred.append("settlement_worker_locked")
        if st == TaskStatus.SETTLED:
            warnings.append("Task already settled — OpenClaw automation may be unnecessary.")
    else:
        warnings.append("No settlement for task_id — create settlement in Console first.")

    if buyer_id:
        cap = await db.get(CapacityModel, buyer_id)
        if cap and cap.total_locked_usdc and cap.total_locked_usdc > 0:
            inferred.append("buyer_lock_capacity")
    if seller_id:
        cap_s = await db.get(CapacityModel, seller_id)
        if cap_s and cap_s.total_locked_usdc and cap_s.total_locked_usdc > 0:
            inferred.append("seller_lock_capacity")

    # De-duplicate while preserving order
    seen: set[str] = set()
    inferred_unique: list[str] = []
    for step in inferred:
        if step not in seen:
            seen.add(step)
            inferred_unique.append(step)

    voucher_status = None
    if voucher_row:
        voucher_status = voucher_row.status

    handoff: dict[str, Any] = {
        "handoff_version": HANDOFF_VERSION,
        "trace_id": (trace_id or "").strip() or f"trace-{task_id}",
        "task_id": task_id,
        "voucher_id": settlement.voucher_id if settlement and settlement.voucher_id else (
            voucher_row.voucher_id if voucher_row else None
        ),
        "buyer_identity_id": buyer_id,
        "seller_identity_id": seller_id,
        "bill_credit_amount": bill_credit,
        "authorization": {
            "voucher_status": voucher_status,
            "manual_console_steps_completed": inferred_unique,
        },
        "notes": (
            "Auto-generated by Karma Console/API — review before OpenClaw automation. "
            "Authorization (voucher accept, Runtime Key mint) must be completed in Console."
        ),
    }

    ok, val_errors, _ = validate_handoff_v1(handoff)
    return {
        "handoff": handoff,
        "validation_ok": ok,
        "validation_errors": val_errors,
        "warnings": warnings,
        "inferred_steps": inferred_unique,
    }
