FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml ./
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev --no-interaction

COPY . .

RUN adduser --disabled-password --gecos "" karma && \
    chown -R karma:karma /app
USER karma

CMD ["celery", "-A", "worker.tasks", "worker", "--loglevel=info"]
