#!/usr/bin/env bash
set -euo pipefail

# Foolproof ETH-chain deploy helper (Sepolia/Mainnet-compatible).
#
# Required env vars:
# - ETH_RPC_URL
# - DEPLOYER_PRIVATE_KEY
# - ADMIN_ADDRESS
#
# Optional env vars:
# - TOKEN_ADDRESS              # If set, script auto calls setTokenAllowed(token, true)
# - PAYEE_ADDRESS              # Used only for UI config helper output
# - OUTPUT_PATH                # default: results/deploy-v01-eth.json
# - UI_CONFIG_PATH             # default: examples/v01-console-config.json
# - WRITE_UI_CONFIG            # default: 1 (write UI helper config)
# - CHAIN_LABEL                # default: eth-like
#
# Usage:
#   ETH_RPC_URL=... DEPLOYER_PRIVATE_KEY=... ADMIN_ADDRESS=... \
#   TOKEN_ADDRESS=... PAYEE_ADDRESS=... \
#   ./scripts/deploy-v01-eth.sh

if [[ -z "${ETH_RPC_URL:-}" || -z "${DEPLOYER_PRIVATE_KEY:-}" || -z "${ADMIN_ADDRESS:-}" ]]; then
  echo "Missing required env vars: ETH_RPC_URL / DEPLOYER_PRIVATE_KEY / ADMIN_ADDRESS"
  exit 1
fi

OUTPUT_PATH="${OUTPUT_PATH:-results/deploy-v01-eth.json}"
UI_CONFIG_PATH="${UI_CONFIG_PATH:-examples/v01-console-config.json}"
WRITE_UI_CONFIG="${WRITE_UI_CONFIG:-1}"
CHAIN_LABEL="${CHAIN_LABEL:-eth-like}"

echo "Deploying SettlementEngine to ${CHAIN_LABEL}..."
deploy_output="$(
  forge create contracts/core/SettlementEngine.sol:SettlementEngine \
    --rpc-url "$ETH_RPC_URL" \
    --private-key "$DEPLOYER_PRIVATE_KEY" \
    --constructor-args "$ADMIN_ADDRESS" \
    --broadcast 2>&1
)"

engine_address="$(printf "%s" "$deploy_output" | rg "Deployed to:" | awk '{print $3}')"
deploy_tx_hash="$(printf "%s" "$deploy_output" | rg "Transaction hash:" | awk '{print $3}')"

if [[ -z "$engine_address" || -z "$deploy_tx_hash" ]]; then
  echo "Deployment failed or output format changed."
  echo "$deploy_output"
  exit 1
fi

allowlist_tx_hash=""
if [[ -n "${TOKEN_ADDRESS:-}" ]]; then
  echo "Setting token allowlist for ${TOKEN_ADDRESS}..."
  allowlist_output="$(
    cast send "$engine_address" "setTokenAllowed(address,bool)" "$TOKEN_ADDRESS" true \
      --rpc-url "$ETH_RPC_URL" \
      --private-key "$DEPLOYER_PRIVATE_KEY" 2>&1
  )"
  allowlist_tx_hash="$(printf "%s" "$allowlist_output" | rg "transactionHash" | awk '{print $2}')"
fi

mkdir -p "$(dirname "$OUTPUT_PATH")"
cat > "$OUTPUT_PATH" <<EOF
{
  "chainLabel": "${CHAIN_LABEL}",
  "engineAddress": "${engine_address}",
  "adminAddress": "${ADMIN_ADDRESS}",
  "tokenAddress": "${TOKEN_ADDRESS:-}",
  "deployTxHash": "${deploy_tx_hash}",
  "allowlistTxHash": "${allowlist_tx_hash}",
  "generatedAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF

if [[ "$WRITE_UI_CONFIG" == "1" ]]; then
  mkdir -p "$(dirname "$UI_CONFIG_PATH")"
  cat > "$UI_CONFIG_PATH" <<EOF
{
  "engineAddress": "${engine_address}",
  "tokenAddress": "${TOKEN_ADDRESS:-}",
  "payeeAddress": "${PAYEE_ADDRESS:-}",
  "notes": "Auto-generated by scripts/deploy-v01-eth.sh. Fill missing values before using the console."
}
EOF
fi

echo
echo "Done."
echo "ENGINE_ADDRESS=${engine_address}"
echo "DEPLOY_TX=${deploy_tx_hash}"
if [[ -n "$allowlist_tx_hash" ]]; then
  echo "ALLOWLIST_TX=${allowlist_tx_hash}"
fi
echo "Artifact written to: ${OUTPUT_PATH}"
if [[ "$WRITE_UI_CONFIG" == "1" ]]; then
  echo "UI helper config: ${UI_CONFIG_PATH}"
fi
echo
echo "Next:"
echo "1) Start UI: python3 -m http.server 8787"
echo "2) Open: http://localhost:8787/examples/v01-metamask-settlement.html"
echo "3) Paste Engine/Token/Payee -> Connect -> Health -> Sign -> Submit"
